@host = localhost:3002

GET http://{{host}} HTTP/1.1

###

POST http://{{host}}/users/register HTTP/1.1
Content-Type: application/json

{
    "name": "Francesco Silvetti",
    "email": "francescosilvetti8@gmail.com",
    "password": "pepe1234"
}

###

POST http://{{host}}/users/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "francescosilvetti8@gmail.com",
    "password": "pepe1234"
}

###

POST http://{{host}}/todos/ HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZjkwMGY5M2M0OTFkNDlmNWQ5NTkwYSIsImlhdCI6MTU2MDI5NzIyOSwiZXhwIjoxNTYwMzAwODI5fQ.VyeKtzrCkLVJ_Ja1Q6OI4vF_-3uXvTWqZFAyDUnChso

{
    "title": "Third todo",
    "desc": "It works, yay!"
}
###

DELETE http://{{host}}/todos/ HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZjkwMGY5M2M0OTFkNDlmNWQ5NTkwYSIsImlhdCI6MTU2MDI5NzIyOSwiZXhwIjoxNTYwMzAwODI5fQ.VyeKtzrCkLVJ_Ja1Q6OI4vF_-3uXvTWqZFAyDUnChso

{
    "todoId": "5cf940920fc05d01911bffa5"
}

###

GET http://{{host}}/todos/ HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZjkwMGY5M2M0OTFkNDlmNWQ5NTkwYSIsImlhdCI6MTU2MDI5NzIyOSwiZXhwIjoxNTYwMzAwODI5fQ.VyeKtzrCkLVJ_Ja1Q6OI4vF_-3uXvTWqZFAyDUnChso
